/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

import ifsc.poo.catalogo.*;

public class App {

    public static void main(String[] args) {

        Controle controle = new Controle();

        controle.executar();

    }
}
